export const levels = [
  [
    "                                    ",
    "                                    ",
    "                                    ",
    "         D6                         ",
    "   A4444901                         ",
    "         01                      B  ",
    "         01                      C  ",
    "         072222222222222222222222222",
    "         073333333333333333333333333",
    "         01      B          B       ",
    "         01      5          C       ",
    "         01      C          EA449   ",
    "         01                         ",
    "         01                         ",
    "         01                         ",
    "         072222226                  ",
    "         833333371A44444444444449   ",
    "   D26    E     01                  ",
    "   83FA449E     01                  ",
    "                01                  ",
  ],
];

export const levelOptions = [
  {
    tileWidth: 48,
    tileHeight: 48,
    tiles: {
      // " ": () => [sprite("grass"), area(), scale(3)],
      0: () => [sprite("left_path"), area(), scale(3)],
      1: () => [sprite("right_path"), area(), scale(3)],
      2: () => [sprite("upper_path"), area(), scale(3)],
      3: () => [sprite("lower_path"), area(), scale(3)],
      4: () => [sprite("small_hori"), area(), scale(3)],
      5: () => [sprite("small_vert"), area(), scale(3)],
      6: () => [sprite("upper_path_right"), area(), scale(3)],
      7: () => [sprite("flat"), area(), scale(3)],
      8: () => [sprite("lower_path_left"), area(), scale(3)],
      9: () => [sprite("small_hori_right"), area(), scale(3)],
      A: () => [sprite("small_hori_left"), area(), scale(3)],
      B: () => [sprite("small_vert_end"), area(), scale(3)],
      C: () => [sprite("small_vert_start"), area(), scale(3)],
      D: () => [sprite("upper_path_left"), area(), scale(3)],
      E: () => [sprite("dot"), area(), scale(3)],
      F: () => [sprite("lower_path_right"), area(), scale(3)],
      G: () => [sprite("lower_path_right"), area(), scale(3)],
    },
  },
];
