import { SCALE_MULTIPLIER } from "../utils/calculations";
const SCALE = 3 * SCALE_MULTIPLIER();

export const levels = [
  [
    "                                    ",
    "                                    ",
    "                   B                ",
    "         D6        5                ",
    "   A4444901        5                ",
    "         01     B  5                ",
    "         01     C  C             E  ",
    "         072222222222222222222222222",
    "         073333333333333333333333333",
    "         01      B          B       ",
    "         01      5          C       ",
    "         01      C          EA449   ",
    "         01    A9E                  ",
    "         01                         ",
    "         01                         ",
    "         072222226                  ",
    "         833333371A44444444444449   ",
    "   D226   E     01                  ",
    "   833FA49E     01                  ",
    "                01                  ",
    "                01                  ",
  ],
  [
    "                                    ",
    "111111111111111111111111111111111111",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
    "1                                   ",
  ],
  [
    "                                    ",
    "                                    ",
    "                      7   6         ",
    "       0             3  5           ",
    "                      4   3         ",
    "               5 6       6          ",
    "                                    ",
    "  5 4 8                             ",
    "    3 6                             ",
    "    87                              ",
    "             0         4  6  0      ",
    "                     4 5 7          ",
    "                         5          ",
    "                      8             ",
    "                                    ",
    "  1    1          4                 ",
    "                                    ",
    "                  4                 ",
    "                                    ",
  ],
];

export const levelOptions = [
  {
    tileWidth: 48 * SCALE_MULTIPLIER(),
    tileHeight: 48 * SCALE_MULTIPLIER(),
    tiles: {
      0: () => [sprite("left_path"), scale(SCALE), anchor("bot")],
      1: () => [sprite("right_path"), scale(SCALE), anchor("bot")],
      2: () => [sprite("upper_path"), scale(SCALE), anchor("bot")],
      3: () => [sprite("lower_path"), scale(SCALE), anchor("bot")],
      4: () => [sprite("small_hori"), scale(SCALE), anchor("bot")],
      5: () => [sprite("small_vert"), scale(SCALE), anchor("bot")],
      6: () => [sprite("upper_path_right"), scale(SCALE), anchor("bot")],
      7: () => [sprite("flat"), scale(SCALE), anchor("bot")],
      8: () => [sprite("lower_path_left"), scale(SCALE), anchor("bot")],
      9: () => [sprite("small_hori_right"), scale(SCALE), anchor("bot")],
      A: () => [sprite("small_hori_left"), scale(SCALE), anchor("bot")],
      B: () => [sprite("small_vert_end"), scale(SCALE), anchor("bot")],
      C: () => [sprite("small_vert_start"), scale(SCALE), anchor("bot")],
      D: () => [sprite("upper_path_left"), scale(SCALE), anchor("bot")],
      E: () => [sprite("dot"), scale(SCALE), anchor("bot")],
      F: () => [sprite("lower_path_right"), scale(SCALE), anchor("bot")],
      G: () => [sprite("lower_path_right"), scale(SCALE), anchor("bot")],
    },
  },
  {
    tileWidth: 48 * SCALE_MULTIPLIER(),
    tileHeight: 48 * SCALE_MULTIPLIER(),
    tiles: {
      0: () => [
        sprite("tree_round"),
        scale(SCALE),
        anchor("bot"),
        area({ scale: [0.4, 0.4] }),
        body({ isStatic: true }),
      ],
      1: () => [
        sprite("tree_point"),
        scale(SCALE),
        anchor("bot"),
        area({ scale: [0.4, 0.4] }),
        body({ isStatic: true }),
      ],
      3: () => [
        sprite("tree_stump"),
        scale(SCALE),
        anchor("bot"),
        area({ scale: [0.7, 0.1] }),
        body({ isStatic: true }),
      ],
      4: () => [
        sprite("rock_one"),
        scale(SCALE),
        anchor("bot"),
        area({ scale: [0.7, 0.1] }),
        body({ isStatic: true }),
      ],
      5: () => [
        sprite("purple_flower"),
        scale(SCALE),
        anchor("bot"),
        area({ scale: [0.4, 0.1] }),
        body({ isStatic: true }),
      ],
      6: () => [
        sprite("blue_flower"),
        scale(SCALE),
        anchor("bot"),
        area({ scale: [0.4, 0.1] }),
        body({ isStatic: true }),
      ],
      7: () => [
        sprite("bush"),
        scale(SCALE),
        anchor("bot"),
        area({ scale: [0.7, 0.1] }),
        body({ isStatic: true }),
      ],
    },
  },
];
